# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0891ffbaad620be0b8e1e6bd2f3179e1a21cfff06b7b61a7b7bf8a58ccf01cc8ec24140655e9a7417dde003290dd4a7adbd251094616193ec765a7a681ccf475

test:
  secret_key_base: 1b14ba5c67f90827e14e7bd96f9910e08cc08b6ac8cede7f679649a2981625fbb4d6216a8c3c6aaa20191316e93a9e1c793e6931f61a1cfaa2a01ba4a8a484f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
